[package]
name = "maylib"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "=0.9.0"
open = "=5.3.2"

[dependencies.sdl2]
version = "=0.37.0"
features = ["image", "ttf", "gfx", "use-vcpkg", "static-link"]

[lints.clippy]
unwrap-used = "forbid"
todo = "forbid"